### ISSUE TITLE
xsi:schemaLocation not working for relative file path

### ISSUE THREAD

**Issue by nullco** [pdavies011010/atom-xmlvalidate#8]
Hi, Im having problems when trying to locate the xml schema using a relative path.

Lets suppose my schema file is in the same directory than my xml instance file.

If I use xsi:schemaLocation="http://tempuri.org/XMLSchema.xsd my_schema.xsd"

atom-xmlvalidate will tell me: "Unable to find schema file: my_schema.xsd"

If instead i use the absoulte path to refer to my file, it works

xsi:schemaLocation="http://tempuri.org/XMLSchema.xsd file:///path/to/my_schema.xsd"

Let me know if you need more info

**Comment by pdavies011010** [comment]
Hi @nullco  You're right, it's definitely expecting a full URL at this point, not a file in the same path (although it should). Should be an easy fix, I'll add it to the list.

**Comment by pdavies011010** [comment]
Merged this fix in #10  This fix is included in version 0.5.0
