### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by gvv90** [pdavies011010/atom-xmlvalidate#9]
Hi, I'm getting this error.

Could someone help me please?

[root@localhost]# apm install atom-xmlvalidate
Installing atom-xmlvalidate to /root/.atom/packages ✗

> libxmljs@0.18.7 install /tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

make: Entering directory '/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
xmljs.target.mk:144: recipe for target 'Release/obj.target/xmljs/src/libxmljs.o' failed
make: Leaving directory '/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build'
Failed to execute '/usr/share/atom/resources/app/apm/bin/node /usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --loglevel=http --module=/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build/Release' (1)
/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9
└── (empty)

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.7 and electron@1.6.15 (electron-v1.6 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-linux-x64.tar.gz 
make: g++: Command not found
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.5.5-300.fc24.x86_64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "build" "--fallback-to-build" "--loglevel=http" "--module=/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build/Release"
gyp ERR! cwd /tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/share/atom/resources/app/apm/bin/node /usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --loglevel=http --module=/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.5.5-300.fc24.x86_64
node-pre-gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/node_modules/atom-xmlvalidate/node_modules/libxmljs
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/package.json'
npm WARN apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9 No description
npm WARN apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9 No repository field.
npm WARN apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9 No README data
npm WARN apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9 No license field.
npm ERR! Linux 4.5.5-300.fc24.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "/tmp/d-118019-14875-kh0nus.qqd7ioogvi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.7 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118019-14875-1rtbj9z.h7fgmygb9/npm-debug.log
npm ERR! code 1

**Comment by pdavies011010** [comment]
Hey @gvv90  
   The thing that's standing out to me is this: `make: g++: Command not found`  Looks like you have installed node-gyp but not the necessary build tools (namely gcc/g++). 
   I assume you're building this on linux? I haven't done that myself but I would be curious to hear how it works out for you if you're able to do it successfully. 
    Under the README.md file I mention that you need to follow the instructions to install node-gyp. Please make sure you also have the other prerequisites installed, listed under the [(Unix Section)](https://github.com/nodejs/node-gyp#installation), namely python 2.7. 
Let me know how it turns out,
Phill

**Comment by pdavies011010** [comment]
Sorry for the delay. There are too many issues with building this module due to it's use of a native (C/C++) XML validation library. I am looking at recreating the module using something like https://www.npmjs.com/package/xmllint now, which is pure javascript and won't have the same build dependency issues. I will update when that work is done.
